### ISSUE TITLE
Multi sample has few issues when adding to Mozilla Gateway

### ISSUE THREAD

**Issue by DavidKarlas** [lillo42/webthing-csharp#5]
I ran Multi sample and tried to add devices to Gateway by using this AddOn: https://github.com/mozilla-iot/thing-url-adapter
1st issue I noticed is that src/Mozilla.IoT.WebThing/Endpoints/PutProperty.cs:58 threw cast exception(trying to assign JsonElement to double)
2nd issue I noticed was that sample/Multi/Things/ExampleDimmableLight.cs:111 `Input` property is `null`
I also noticed that all href links are of style `things/{thing}/...` but src/Mozilla.IoT.WebThing/ServiceRouteBuilder.cs:30 seems to prepand `/{{thing}}` instead of `/things/{thing}` or am I holding it wrong?

**Comment by lillo42** [comment]
@DavidKarlas I fixes it on PR https://github.com/lillo42/webthing-csharp/pull/12 and I release a preview version of this fixes. I'm making more test with Mozilla Gateway

https://www.nuget.org/packages/Mozilla.IoT.WebThing/1.0.1-preview1

**Comment by lillo42** [comment]
new vesion release  - 1.0.1
