### ISSUE TITLE
Status: Offline....

### ISSUE THREAD

**Issue by MadsHHLund** [lillo42/webthing-csharp#6]
I have installed “Mozzila.IoT.WebThing” on Visual Studio .netCore.

The communication with the two test examples works, but in the Gateway, their status is always “greyed out” = “disconnected”.

Do you have any idea where to look for that error?

**Comment by lillo42** [comment]
To works it's necessary add in Startup ```app.UseWebSockets()```

see: https://github.com/lillo42/webthing-csharp/blob/release-1.0/sample/Multi/Startup.cs

I added this in sample
